runtime: java
env: flex
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5

handlers:
  - url: /.*
    script: this field is required, but ignored
    secure: always

env_variables:
  SPRING_DATASOURCE_URL: jdbc:h2:mem:Course_data
  SPRING_DATASOURCE_USERNAME: piyush
  SPRING_DATASOURCE_PASSWORD: Jaibalaji@28
  SERVER_PORT: 9090

