steps:
  # Step 1: Checkout the code from the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/p1yushsharma/api']

  # Step 2: Run Maven build
  - name: 'maven:3.6.3-jdk-8'
    args: ['mvn', 'clean', 'install']
    dir: 'api'

  # Step 3: Run unit tests
  - name: 'maven:3.6.3-jdk-8'
    args: ['mvn', 'test']
    dir: 'api'

  # Step 4: Deploying to Google App Engine if applicable
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: 'api'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/your-credentials.json'

# Optionally specify artifacts, logs, or post-deployment scripts
artifacts:
  objects:
    paths:
      - 'api/target/*.jar'
